#!/bin/bash -p
# Copyright Yahoo Inc, 2021.
# Licensed under the terms of the Apache-2.0 license.
# For terms, see the LICENSE file at https://github.com/yahoo/tunitas-montara/blob/master/LICENSE
# For terms, see the LICENSE file at https://git.tunitas.technology/all/services/montara/tree/LICENSE
: ${with_build:=/build}
: ${with_worktrees:=${with_build?}/worktrees}
: ${TAG:=CURRENT}

: ${with_module_rigging_app=${with_module_rigging_app:-${with_worktrees?}/rigging-app/v0.${TAG?}}}
: ${with_module_rigging_core=${with_module_rigging_core:-${with_worktrees?}/rigging-core/v2.${TAG?}}}
: ${with_module_rigging=${with_module_rigging_core?}}

: ${with_siblings=$(realpath ${0%/*}/../..)}
if [[ -f ${with_siblings?}/basics/configure.ac ]] ; then
    : ${with_tunitas_basics:=${with_siblings?}/basics}
else
    : ${with_tunitas_basics:=${with_worktrees?}/basics/v2.${TAG?}}
fi
if [[ -f ${with_siblings?}/butano/configure.ac ]] ; then
    : ${with_tunitas_butano:=${with_siblings?}/butano}
else
    for v in v0 v1 v2 ; do
       : ${with_tunitas_butano:=${with_worktrees?}/butano/$v.${TAG?}}
    done
fi

if [[ -d ${with_worktrees?}/cli-core ]] ; then
    : ${with_module_cli_core:=${with_worktrees?}/cli-core/v2.${TAG?}}
    : ${with_module_options=${with_module_cli_core?}}
else
    : ${with_module_options:=${with_worktrees?}/options/v2.${TAG?}}
    : ${with_module_cli_core:=${with_module_options?}}
fi
if [[ -d ${with_worktrees?}/level ]] ; then
    : ${with_module_level:=${with_worktrees?}/level/v0.${TAG?}}
    : ${with_module_leveldb=${with_module_level?}}
else
    : ${with_module_leveldb:=${with_worktrees?}/leveldb/v0.${TAG?}}
    : ${with_module_level:=${with_module_leveldb?}}
fi

with_build=${with_build?} \
with_nearby=${with_nearby:-${with_build?}/scold} \
with_hypogeal_twilight=${with_hypogeal_twilight:-${with_worktrees?}/hypogeal-twilight/v0.${TAG?}} \
with_module_ares=${with_module_ares:-${with_worktrees?}/ares/v0.${TAG?}} \
with_apache_httpd_api=${with_apache_httpd_api:-${with_worktrees?}/apache-httpd-api/v0.${TAG?}} \
with_module_langu=${with_module_langu:-${with_worktrees?}/langu/v0.${TAG?}} \
with_module_json=${with_module_json:-${with_worktrees?}/json/v0.${TAG?}} \
with_module_level=${with_module_level?} \
with_module_leveldb=${with_module_leveldb?} \
with_module_nonstd=${with_module_nonstd:-${with_worktrees?}/nonstd/v2.${TAG?}} \
with_module_openssl=${with_module_openssl:-${with_worktrees?}/openssl/v0.${TAG?}} \
with_module_rabinpoly=${with_module_rabinpoly:-${with_worktrees?}/rabinpoly/v0.${TAG?}} \
with_module_shell=${with_module_shell:-${with_worktrees?}/shell/v2.${TAG?}} \
with_module_sqlite=${with_module_sqlite:-${with_worktrees?}/sqlite/v0.${TAG?}} \
with_module_sys=${with_module_sys:-${with_worktrees?}/sys/v2.${TAG?}} \
with_module_uuid=${with_module_uuid:-${with_worktrees?}/uuid/v0.${TAG?}} \
\
with_module_cli_core=${with_module_cli_core?} \
with_module_options=${with_module_options?} \
\
with_module_rigging_core=${with_module_rigging_core?} \
with_module_rigging=${with_module_rigging?} \
with_nonstd_cppunit=${with_nonstd_cppunit:-no} \
with_module_cppunit=${with_module_cppunit:-no} \
\
with_module_boost=${with_module_boost:-no} \
with_module_c=${with_module_c:-no} \
with_module_format=${with_module_format:-no} \
with_module_ip=${with_module_ip:-no} \
with_module_posix=${with_module_posix:-no} \
with_module_slurp=${with_module_slurp:-no} \
with_module_std=${with_module_std:-no} \
with_module_string=${with_module_string:-no} \
\
with_microhttpd__=${with_microhttpd__:-${with_worktrees?}/microhttpd++/v0.${TAG?}} \
with_microhttpd=${with_microhttpd:-${with_worktrees?}/microhttpd++/v0.${TAG?}} \
\
with_temerarious_flagship=${with_temerarious_flagship:-${with_worktrees?}/temerarious-flagship/v2.${TAG?}} \
with_tunitas_basics=${with_tunitas_basics?} \
with_tunitas_butano=${with_tunitas_butano?} \
\
exec ${0%/*}/nearby
