#!/bin/sh

function do_curl() {
    declare -a argv=(curl --trace-ascii - --header 'Host: ping.example' "$@")
    echo "run ${argv[@]}"
    "${argv[@]}"
    local e=$?
    echo "${argv[0]} exit $e"
    return $e
}

function show_last_few() {
    echo "--- the last few in $1 -------------------------------------------"
    tail -5 $1
}

echo
echo "--- OPTIONS -------------------------------------------"
do_curl -X OPTIONS http://localhost:8888/apanolio
echo "--- GET -------------------------------------------"
do_curl http://localhost:8888/apanolio
do_curl http://localhost:8888/apanolio/
do_curl http://localhost:8888/apanolio/123
echo "--- POST -------------------------------------------"
do_curl -d post-that http://localhost:8888/apanolio
echo "--- PUT -------------------------------------------"
do_curl -X PUT -d put-that http://localhost:8888/apanolio
echo

# var probably contains data files (the apanolio local storage)
ls -als ${0%/*}/{var,logs}
show_last_few logs/access_log
show_last_few logs/error_log
